# Generated by Django 3.2.13 on 2022-07-18 20:53

import account.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='username')),
                ('email', models.EmailField(max_length=128, unique=True, verbose_name='email')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to=account.models.profile_image_path)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='account.account')),
                ('character_type', models.CharField(choices=[('warrior', 'warrior'), ('mage', 'mage'), ('scout', 'scout')], default='', max_length=20, verbose_name='character type')),
                ('level', models.DecimalField(decimal_places=0, default=1, max_digits=19, verbose_name='level')),
                ('strength', models.DecimalField(decimal_places=0, default=8, max_digits=19, verbose_name='strength')),
                ('skill', models.DecimalField(decimal_places=0, default=6, max_digits=19, verbose_name='skill')),
                ('intelligence', models.DecimalField(decimal_places=0, default=7, max_digits=19, verbose_name='intelligence')),
                ('health_point', models.DecimalField(decimal_places=0, default=10, max_digits=19, verbose_name='health point')),
                ('fortune', models.DecimalField(decimal_places=0, default=8, max_digits=19, verbose_name='fortune')),
                ('shield', models.DecimalField(decimal_places=0, default=0, max_digits=19, verbose_name='shield')),
                ('rank', models.DecimalField(blank=True, decimal_places=0, max_digits=19, null=True, verbose_name='rank')),
                ('honor', models.DecimalField(decimal_places=0, default=1, max_digits=19, verbose_name='honor')),
                ('gold', models.DecimalField(decimal_places=0, default=100, max_digits=20, verbose_name='gold')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterHistory',
            fields=[
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='account.account')),
                ('matches_played', models.DecimalField(decimal_places=0, default=0, max_digits=19, verbose_name='matches played')),
            ],
        ),
    ]
