# Generated by Django 3.2.13 on 2022-07-19 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='team',
        ),
    ]
