# Generated by Django 3.2.13 on 2022-08-18 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_account_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(error_messages={'Invalid': 'Az email cím nem megfelelő'}, max_length=128, unique=True, verbose_name='email'),
        ),
    ]
