# Generated by Django 3.2.13 on 2022-08-19 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_account_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='current_xp',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20, verbose_name='xp'),
        ),
        migrations.AddField(
            model_name='character',
            name='next_level_xp',
            field=models.DecimalField(decimal_places=0, default=150, max_digits=20, verbose_name='next level xp'),
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(max_length=128, unique=True, verbose_name='email'),
        ),
    ]
