# Generated by Django 3.2.13 on 2022-08-20 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20220819_1253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='characterhistory',
            old_name='matches_played',
            new_name='fights_played',
        ),
        migrations.AddField(
            model_name='characterhistory',
            name='fights_lost',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=19, verbose_name='matches won'),
        ),
        migrations.AddField(
            model_name='characterhistory',
            name='fights_won',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=19, verbose_name='matches won'),
        ),
    ]
