# Generated by Django 3.2.13 on 2022-08-20 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20220820_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterhistory',
            name='fights_lost',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=19, verbose_name='fights lost'),
        ),
        migrations.AlterField(
            model_name='characterhistory',
            name='fights_played',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=19, verbose_name='fights played'),
        ),
        migrations.AlterField(
            model_name='characterhistory',
            name='fights_won',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=19, verbose_name='fights won'),
        ),
    ]
