# Generated by Django 3.2.13 on 2022-08-25 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_account_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='shield',
        ),
    ]
