# Generated by Django 3.2.13 on 2022-08-08 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_chat', '0002_unreadpublicchatroommessages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unreadpublicchatroommessages',
            name='last_seen_time',
            field=models.DateTimeField(null=True),
        ),
    ]
