# Generated by Django 3.2.13 on 2022-10-06 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public_chat', '0003_alter_unreadpublicchatroommessages_last_seen_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unreadpublicchatroommessages',
            name='last_seen_time',
        ),
    ]
