# Generated by Django 3.2.13 on 2022-10-06 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_chat', '0004_remove_unreadpublicchatroommessages_last_seen_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='unreadpublicchatroommessages',
            name='last_seen_time',
            field=models.DateTimeField(null=True),
        ),
    ]
