# Generated by Django 3.2.13 on 2022-08-08 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='verb',
            new_name='notification_text',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='notification_url',
        ),
    ]
