# Generated by Django 3.2.13 on 2022-07-18 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
    ]
