# Generated by Django 3.2.13 on 2022-08-08 13:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('team', '0010_unreadteammessages'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='users_in_chat',
            field=models.ManyToManyField(related_name='users_in_chat', to=settings.AUTH_USER_MODEL),
        ),
    ]
