# Generated by Django 3.2.13 on 2022-09-02 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0011_team_users_in_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='rank',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=19, null=True, verbose_name='rank'),
        ),
    ]
