# Generated by Django 3.2.13 on 2022-09-14 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0016_alter_teamjoinrequest_request_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teamjoinrequest',
            options={},
        ),
    ]
