# Generated by Django 3.2.13 on 2022-09-18 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0017_alter_teamjoinrequest_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='honor',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=19, verbose_name='team honor'),
        ),
    ]
