# Generated by Django 3.2.13 on 2022-10-06 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0018_team_honor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unreadteammessages',
            name='last_seen_time',
        ),
    ]
