# Generated by Django 3.2.13 on 2022-08-07 14:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('private_chat', '0002_unreadprivatechatroommessages'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatechatroom',
            name='current_users',
            field=models.ManyToManyField(blank=True, related_name='current_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
