# Generated by Django 3.2.13 on 2022-08-08 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('private_chat', '0003_privatechatroom_current_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unreadprivatechatroommessages',
            old_name='sending_time',
            new_name='last_seen_time',
        ),
    ]
