# Generated by Django 3.2.13 on 2022-10-06 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('private_chat', '0005_alter_unreadprivatechatroommessages_last_seen_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unreadprivatechatroommessages',
            name='last_seen_time',
        ),
    ]
