# Generated by Django 3.2.13 on 2022-08-21 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20220820_1323'),
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arena',
            name='attacker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attacker', to='account.character'),
        ),
        migrations.AlterField(
            model_name='arena',
            name='defender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defender', to='account.character'),
        ),
        migrations.AlterField(
            model_name='arena',
            name='winner_of_fight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='account.character'),
        ),
    ]
